### ISSUE TITLE
logo design Proposal SymmetryGroupPuzzle

### ISSUE THREAD

**Issue by Pelikens** [spencerparkin/SymmetryGroupPuzzle#11]
Hello! I want to contribute on your project SymmetryGroupPuzzle with making free logo design. What do you think about it?

Best Regards,
Ksenia
Graphics Designer

**Comment by spencerparkin** [comment]
Sure.  Go ahead.  Thanks.

**Comment by Pelikens** [comment]
Hi and thanks for your reply! That's great! Do you have any special requirements for the logo? Any symbols that should be included? And how do you plan to use the logo? On your web site and etc?

**Comment by spencerparkin** [comment]
Currently there is no icon that appears in the upper-left hand corner of
the web-browser when visiting the page.  For example, if you go to
stackoverflow.com or gmail.com, you see the following...




I think I would need a .PNG file of dimensions 32x32.  Take as much
creative liberty otherwise.  I suppose whatever it is, it should have
symmetry.

Thanks again.
--Sp

**Comment by Pelikens** [comment]
Hi, here is an option for the logo and example on the web site.  Please, let me know what do you think? 
![image](https://user-images.githubusercontent.com/39441298/43021528-94f98ef0-8c6c-11e8-91bc-1ee35edc4964.png)
![image](https://user-images.githubusercontent.com/39441298/43021553-b43cdb00-8c6c-11e8-89cf-2a6f827a29ee.png)

**Comment by spencerparkin** [comment]
Thank you!  I will use 1.3.  I can also put it at the head of the page.  Thanks again!

**Comment by Pelikens** [comment]
I uploaded all the required files and created a pull-request. Please merge it if everything is Ok

**Comment by Pelikens** [comment]
Thank you for your collaboration and good luck with your project!
